In [1]:
%matplotlib inline

In [2]:
# Inputs:
# outputs:

In [43]:
from shapely.geometry import LineString

import numpy as np
import cv2

import sys
sys.path.append("/home/jasonraiti/Documents/GitHub/USC_REU/Project_Files/Jasons_Functions/")

from open_or_show_image import *

from trim_edges import *

from erosion_dilation import * 

from drawline import *

In [44]:

# path to images
path1 = r'./MAPS/Map_originals/Lake_Murray_Map_Originals/e_d_image4.png'

# path2 = r'./MAPS/Map_Skeletons/Ibrahim_test_skeletons/preprocessing/trimmed/trimmed_e4_d4___MAPS_Map_originals_Ibrahim_Test_ibrahim_test_bw_png_png_skeleton_lee94_png.png' 

path2 = r'./zigzag_full.png' 

path3 = r'./inverse_skeletons/e1_d0_negative_skeleton_png_png_medial_axis.png'

#original image
image1 = open_image(path1)

#skeleton image
image2 = open_image(path2)

# #inverse skel
# option = 2 # 1 = erode first 2 = dialate first 
# num_erosions = 0
# num_dilations = 1
# image3 , name = erosion_dilation(path3,option,num_erosions,num_dilations)

image3 = open_image(path3)

black_image = np.zeros((image1.shape[0],image1.shape[1])) # get black background 
print(image1.shape)

found image at :  ./MAPS/Map_originals/Lake_Murray_Map_Originals/e_d_image4.png
found image at :  ./zigzag_full.png
found image at :  ./inverse_skeletons/e1_d0_negative_skeleton_png_png_medial_axis.png
(403, 341)


In [45]:


line1 = LineString([(0,0), (1,0), (1,1)])
line2 = LineString([(0,1), (1,1)])

print(line1.intersection(line2))

POINT (1 1)


In [46]:
    
    
    
    # print(boundary_image.shape) #(322,329)
    top_side = LineString([(0,0) , (0,image1.shape[1])])
    right_side = LineString([(0,image1.shape[1]) , (image1.shape[0],image1.shape[1])])
    bottom_side = LineString([(image1.shape[0],image1.shape[1]) , (image1.shape[0],0)]) 
    left_side = LineString([(image1.shape[0],0) , (0,0)])  # WARNING - the graph is in y,x format (also y is sign is switched indexed at top left) , this is in y,x 





    
    start_point_line = LineString([(-100,100) , (-100,50)]) 
    end_point_line = LineString([(-200,50) , (-50,150)]) 
    
    # print(start_point + normalized_slope_vector)
    # # print(end_point + normalized_slope_vector)
    # start_point_line = ( start_point + normalized_slope_vector , start_point)
    # end_point_line = (end_point + normalized_slope_vector , start_point)
    
    print(top_side.intersection(top_side))
    print(top_side.intersection(right_side))
    print(top_side.intersection(bottom_side))
    print(top_side.intersection(left_side))


    # print(type(top_side.intersection(left_side).x))
    # left_intersect = np.array( [ top_side.intersection(left_side).x, top_side.intersection(left_side).y ] )
    # print(left_intersect)
    # right_intersect = np.array( [top_side.intersection(right_side).x, top_side.intersection(right_side).y] )
    # print(right_intersect)

    near_bottom_side = LineString([(image1.shape[0]-100,image1.shape[1]) , (image1.shape[0],0)]) 
    bottom_side = near_bottom_side

    # left_intersect = np.array( [ top_side.intersection(left_side).x, top_side.intersection(left_side).y ] )
    # print(left_intersect)
    # right_intersect = np.array( [top_side.intersection(right_side).x, top_side.intersection(right_side).y] )
    # print(right_intersect)
    

    left_intersect = np.array( [ bottom_side.intersection(left_side).x , bottom_side.intersection(left_side).y ] )
    print(left_intersect)
    right_intersect = np.array( [ bottom_side.intersection(right_side).x , bottom_side.intersection(right_side).y ] )
    print(right_intersect)
    

    image = drawline(left_intersect , right_intersect , black_image)

    print(image)

    show_image(image)
    for i in image:
        for j in i:
            if j > 0 :
                print('we good')



    # print (line_intersection(top_side, top_side))
    # print (line_intersection(start_point_line, right_side))
    # print (line_intersection(start_point_line, bottom_side))
    # print (line_intersection(start_point_line, left_side))
    
    

LINESTRING (0 0, 0 341)
POINT (0 341)
LINESTRING EMPTY
POINT (0 0)
[403.   0.]
[303. 341.]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good
we good


In [51]:
    # print(boundary_image.shape) #(322,329)
    top_side = LineString([(0,0) , (0,image1.shape[1])])
    right_side = LineString([(0,image1.shape[1]) , (image1.shape[0],image1.shape[1])])
    bottom_side = LineString([(image1.shape[0],image1.shape[1]) , (image1.shape[0],0)]) 
    left_side = LineString([(image1.shape[0],0) , (0,0)])  # WARNING - the graph is in y,x format (also y is sign is switched indexed at top left) , this is in y,x 



    black_image = np.zeros((image1.shape[0],image1.shape[1])) # get black background 
    print(image1.shape) 

    # ---------------- find intersects 
    # near_bottom_side = LineString([(image1.shape[0]-100,image1.shape[1]) , (image1.shape[0],0)]) 
    # bottom_side = near_bottom_side

    right_side = LineString([(0,image1.shape[1]) , (image1.shape[0],image1.shape[1]-100)])

    left_intersect = np.array( [ bottom_side.intersection(left_side).x , bottom_side.intersection(left_side).y ] )
    print(left_intersect)
    right_intersect = np.array( [ bottom_side.intersection(right_side).x , bottom_side.intersection(right_side).y ] )
    print(right_intersect)
    




    image = drawline(left_intersect , right_intersect , black_image)

    print(image)

    show_image(image)
    for i in image:
        for j in i:
            if j > 0 :
                print('we good')


(403, 341)
[403.   0.]
[403. 241.]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
